INSERT INTO Role_Type_Code(Role_Name) VALUES ('University Admin'); 
INSERT INTO Role_Type_Code(Role_Name) VALUES ('Department Admin');
INSERT INTO Role_Type_Code(Role_Name) VALUES ('Student');
INSERT INTO Role_Type_Code(Role_Name) VALUES ('Tutor');
INSERT INTO Role_Type_Code(Role_Name) VALUES ('Admission Officer');
INSERT INTO Course_Type_Code(Course_Name) VALUES ('Under-Graduate');
INSERT INTO Course_Type_Code(Course_Name) VALUES ('Post-Graduate');
INSERT INTO Course_Year(Course_Year_Description) VALUES ('1st Year');
INSERT INTO Course_Year(Course_Year_Description) VALUES ('2nd Year');
INSERT INTO Course_Year(Course_Year_Description) VALUES ('3rd Year');
INSERT INTO Exam_Type_Code(Exam_Type_Name) VALUES ('In-Course Component');
INSERT INTO Exam_Type_Code(Exam_Type_Name) VALUES ('Examination');
INSERT INTO Status_Type_Code(Status_Name) VALUES ('Approved');
INSERT INTO Status_Type_Code(Status_Name) VALUES ('Declined');
INSERT INTO Status_Type_Code(Status_Name) VALUES ('Pending');
INSERT INTO Status_Type_Code(Status_Name) VALUES ('In Progress');
INSERT INTO Request_Type_Code(Request_Name) VALUES ('Course Enrollment Request');
INSERT INTO User(User_Name,Role_Type_Code_Id,Password,First_Name,Last_Name) VALUES ('aj',1,'admin', 'Dean', 'Jones');
INSERT INTO User(User_Name,Role_Type_Code_Id,Password,First_Name,Last_Name) VALUES ('sj',2,'admin', 'Saimo', 'Jones');